import type { Metadata } from "next";

import "./globals.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import { CartProvider } from "@/contexts/CartContext";








export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  
  return (
    <html lang="en">
      <body className="overflow-x-none">
        <CartProvider>
      <NavBar navStyle=""/>
        {children}

       


        <Footer/>
       
        </CartProvider>
        </body>
    </html>
  );
}
